const menuitems = [
    {
      category: 'South Indian Dish',
      name: 'Briyani',
      image: 'public/briyani.jpeg',
      price: '₹120.00',
      rating: 4.5,
     
    },
    {
      category: 'South Indian Dish',
      name: 'Mutton Briyani',
      image: 'public/mutton briyani.jpeg',
      price: '₹180.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Chicken lolly pop',
      image: 'public/chicken lolly pop.jpeg',
      price: '₹100.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Fried rice',
      image: 'public/fried rice.jpeg',
      price: '₹80.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Chicken dosa',
      image: 'public/chicken dosa.jpeg',
      price: '₹90.00',
      rating: 4.5,
    },
  
    {
      category: 'South Indian Dish',
      name: 'Noodels',
      image: 'public/noodels.jpeg',
      price: '₹60.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Porotta',
      image: 'public/porotta.jpeg',
      price: 'Set ₹30.00',
    },
    {
      category: 'South Indian Dish',
      name: 'Kottu Poratto',
      image: 'public/kottu poratto.jpeg',
      price: '₹120.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Chicken 65',
      image: 'public/Chicken 65.jpeg',
      price: '₹120.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Chicken Curry Rice',
      image: 'public/Chicken curry Rice.jpg',
      price: '₹120.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Veg Briyani',
      image: 'public/veg briyani.jpeg',
      price: '₹80.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Poori',
      image: 'public/poori.jpeg',
      price: 'Set ₹35.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Egg Dosa',
      image: 'public/egg dosa.jpeg',
      price: '₹50.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Bun Porotta',
      image: 'public/bun porotta.jpeg',
      price: 'Set ₹50.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Meals',
      image: 'public/meals.jpeg',
      price: '₹100.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Kerala Prawn Curry',
      image: 'public/kerala-prawn-curry.webp',
      price: '₹200.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Egg Dosa',
      image: 'public/egg dosa.jpeg',
      price: '₹80.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Chicken Kottu Porotta',
      image: 'public/chicken kpottu poroota.jpeg',
      price: '₹150.00',
      rating: 4.5,
    },
    {
      category: 'South Indian Dish',
      name: 'Prawn Briyani',
      image: 'public/prawn briyani.jpeg',
      price: '₹150.00',
      rating: 4.5,
    },

    {
        category: 'Ice Cream',
        name: 'Choco cone',
        image: 'public/dark choco.jpeg',
        price: '₹60.00',
        rating: 4.5,
      },
      {
        category: 'Ice Cream',
        name: 'Strawberry cone',
        image: 'public/strawberry.jpeg',
        price: '₹40.00',
        rating: 4.5,
      },

      {
        category: 'Ice Cream',
        name: 'Pista',
        image: 'public/pista.jpeg',
        price: '₹45.00',
        rating: 4.5,
      },
      {
        category: 'Ice Cream',
        name: 'Dark Choco',
        image: 'public/dark choco.jpeg',
        price: '₹60.00',
        rating: 4.5,
      },
      {
        category: 'Ice Cream',
        name: 'Black Current',
        image: 'public/black current.jpeg',
        price: '₹45.00',
        rating: 4.5,
      },
      {
        category: 'Hotel Specials',
        name: 'Briyani',
        image: 'public/briyani.jpeg',
        price: '₹120.00',
        rating: 4.5,
      },
      {
        category: 'Hotel Specials',
        name: 'Mutton Briyani',
        image: 'public/mutton briyani.jpeg',
        price: '₹180.00',
        rating: 4.5,
      },
      {
        category: 'Hotel Specials',
        name: 'Noodels',
        image: 'public/noodels.jpeg',
        price: '₹60.00',
        rating: 4.5,
      },

      {
        category: 'Fast food',
        name: 'Burger',
        image: 'public/burger.jpeg',
        price: '₹80.00',
        rating: 4.5,
      },

      {
        category: 'Fast food',
        name: 'french fries',
        image: 'public/french fries.jpeg',
        price: '₹100.00',
        rating: 4.5,
      },
      {
        category: 'Fast food',
        name: 'hot dog',
        image: 'public/hot dog.jpeg',
        price: '₹90.00',
        rating: 4.5,
      },
      {
        category: 'Fast food',
        name: 'Pizza',
        image: 'public/pizza.jpeg',
        price: '₹120.00',
        rating: 4.5,
      },
      {
        category: 'Fast food',
        name: 'Burrito',
        image: 'public/Burrito.JPG',
        price: '₹150.00',
        rating: 4.5,
      },
      {
        category: 'South Indian Dish',
        name: 'chapatti',
        image: 'public/chappati.jpeg',
        price: '₹40.00',
        rating: 4.5,
      },
      {
        category: 'South Indian Dish',
        name: 'strwaberry juice',
        image: 'public/juice.jpeg',
        price: '₹40.00',
        rating: 4.5,
      }
  ];
  export default menuitems;

  

  